local modpath = minetest.get_modpath("derilict_building")
dofile(modpath.."/copper_pipes.lua")
dofile(modpath.."/girder.lua")
dofile(modpath.."/large_fans.lua")
dofile(modpath.."/panel_walls.lua")
dofile(modpath.."/vent.lua")
